# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: himanshu077
# "service" is the name of this project. This will also be added to your AWS resource names.
service: Twitter-Backend

plugins:
  - serverless-appsync-plugin

provider:
  name: aws
  runtime: nodejs20.x

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(serverless.appsync-api.yml)}
